import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Sidenavbar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        <div style={{ display: "flex", minHeight: "80vh" }}>
          {/* Sidebar */}
          <div style={{ width: "250px" }}>
            <Sidenavbar />
          </div>

          {/* Main Content */}
          <main style={{ flex: 1, padding: "20px" }}>
            {children}
          </main>
        </div>

        <Footer />
      </body>
    </html>
  );
}
